name=LCDDisplay
version=0.0.0
author=mumanchu
maintainer=mumanchu <info@muman.ch>
sentence=Library for LCD Displays using I2C, PCF8574, MCP23008
paragraph=
category=Display
includes=LCDDisplay.h
url=https://github.com/mumanchu/LCDDisplay
architectures=*

